---
name: Release

on:
  release:
    types: [published]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - run: npm ci
    - run: npm run build --if-present
      env:
        CI: false
        REACT_APP_API_KEY: 'https://rest.assetmantle.one'
        REACT_APP_TENDERMINT_RPC_ENDPOINT: 'https://rpc.assetmantle.one'
        REACT_APP_WEBSITE_URL: 'https://wallet.assetmantle.one'
        REACT_APP_EXPLORER_API: 'https://explorer.assetmantle.one'
        REACT_APP_MAIL_CHIMP_URL: ''
        REACT_APP_CHAIN_ID: 'mantle-1'
        REACT_APP_CHAIN_NAME: 'AssetMantle'
        REACT_APP_IBC_CONFIG: 'ibcMainnet.json'
        REACT_APP_GA_TRACKING_ID: ''
        REACT_APP_SENTRY_API: ''
    - name: Publish
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_TOKEN }}
        environment: 'mainnet-wallet'
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
